# Generated by Django 4.2.30 on 2026-04-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesopsicologico',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Identificación'),
        ),
        migrations.AddField(
            model_name='procesopsicologico',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía (CC)'), ('TI', 'Tarjeta de Identidad (TI)')], max_length=2, null=True, verbose_name='Tipo de Identificación'),
        ),
    ]
