# Generated by Django 4.2.30 on 2026-04-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_procesopsicologico_numero_identificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesopsicologico',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fin'),
        ),
    ]
