# Generated by Django 4.2.30 on 2026-04-09 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0003_procesopsicologico_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaforo',
            name='respuesta_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_hijas', to='matriculas.respuestaforo'),
        ),
    ]
