# Generated by Django 4.2.30 on 2026-04-09 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matriculas', '0004_respuestaforo_respuesta_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MensajeForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='matriculas.conversacion')),
            ],
            options={
                'verbose_name': 'Mensaje del Foro',
                'verbose_name_plural': 'Mensajes del Foro',
                'ordering': ['fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='temaforo',
            name='reacciones',
        ),
        migrations.DeleteModel(
            name='RespuestaForo',
        ),
        migrations.AddField(
            model_name='conversacion',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='matriculas.temaforo'),
        ),
        migrations.AlterUniqueTogether(
            name='conversacion',
            unique_together={('tema', 'profesor')},
        ),
    ]
