# Generated by Django 4.2.30 on 2026-04-10 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matriculas', '0005_conversacion_mensajeforo_remove_temaforo_reacciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='psicologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_como_psicologo', to=settings.AUTH_USER_MODEL),
        ),
    ]
