# Generated by Django 4.2.30 on 2026-04-10 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matriculas', '0006_conversacion_psicologo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Entrada de Historia Clínica')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_historia', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='matriculas.procesopsicologico')),
            ],
            options={
                'verbose_name': 'Entrada de Historia Clínica',
                'verbose_name_plural': 'Entradas de Historia Clínica',
                'ordering': ['fecha'],
            },
        ),
    ]
