# Generated by Django 4.2.30 on 2026-04-17 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matriculas', '0007_historiaclinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cita', 'Recordatorio de Cita'), ('sistema', 'Sistema')], default='sistema', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('enlace', models.CharField(blank=True, max_length=200)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cita', models.CharField(choices=[('cita_padres', 'Cita con Padres de Familia'), ('seguimiento', 'Seguimiento de Estudiante'), ('reunion_coordinador', 'Reunión con Coordinador'), ('reunion_rector', 'Reunión con Rector'), ('reunion_profesor', 'Reunión con Profesor'), ('reunion_convivencia', 'Reunión de Convivencia')], max_length=30, verbose_name='Tipo de Cita')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('duracion', models.PositiveIntegerField(default=60, verbose_name='Duración (minutos)')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Color')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('recordar', models.BooleanField(default=True, verbose_name='Recordar 1 hora antes')),
                ('notificado', models.BooleanField(default=False, verbose_name='Notificación enviada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='matriculas.procesopsicologico')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='CalendarioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicio_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0, verbose_name='Primer día de la semana')),
                ('hora_inicio', models.TimeField(default='07:00', verbose_name='Hora de inicio de atención')),
                ('hora_fin', models.TimeField(default='17:00', verbose_name='Hora de fin de atención')),
                ('psicologo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_calendario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Calendario',
                'verbose_name_plural': 'Configuraciones del Calendario',
            },
        ),
        migrations.CreateModel(
            name='DiaNoHabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('es_recurrente', models.BooleanField(default=False, verbose_name='Se repite anualmente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_no_habiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Día No Hábil',
                'verbose_name_plural': 'Días No Hábiles',
                'ordering': ['fecha'],
                'unique_together': {('psicologo', 'fecha')},
            },
        ),
    ]
