# Generated by Django 4.2.30 on 2026-04-17 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matriculas', '0008_notificacion_cita_calendarioconfig_dianohabil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTipoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cita', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_tipos_cita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Tipo de Cita',
                'verbose_name_plural': 'Configuraciones de Tipos de Cita',
                'unique_together': {('psicologo', 'tipo_cita')},
            },
        ),
    ]
