# Generated by Django 4.2.30 on 2026-04-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0009_configtipocita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configtipocita',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Tipo de Cita', 'verbose_name_plural': 'Tipos de Cita'},
        ),
        migrations.AlterUniqueTogether(
            name='configtipocita',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='configtipocita',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='configtipocita',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(max_length=100, verbose_name='Tipo de Cita'),
        ),
        migrations.AlterField(
            model_name='configtipocita',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='configtipocita',
            name='color',
            field=models.CharField(default='#8b2be2', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='configtipocita',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Tipo'),
        ),
        migrations.RemoveField(
            model_name='configtipocita',
            name='tipo_cita',
        ),
    ]
