# Generated by Django 6.0.2 on 2026-04-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0010_alter_configtipocita_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='libros/covers/', verbose_name='Imagen de portada'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='color_portada',
            field=models.CharField(default='#8b2be2', max_length=7, verbose_name='Color de portada (si no hay imagen)'),
        ),
    ]
