# Generated by Django 4.2.30 on 2026-05-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0011_libro_imagen_portada_alter_libro_color_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('psicologo', 'Psicólogo'), ('profesor', 'Profesor'), ('admin', 'Administrador')], default='profesor', max_length=20),
        ),
    ]
