# Generated by Django 4.2.11 on 2026-05-27 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matriculas', '0013_google_credentials_emaillog_cita_google_event_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consejoproceso',
            options={'ordering': ['-fecha'], 'verbose_name': 'Ajuste Razonable', 'verbose_name_plural': 'Ajustes Razonables'},
        ),
        migrations.AlterField(
            model_name='consejoproceso',
            name='texto',
            field=models.TextField(verbose_name='Ajuste Razonable'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('url', models.URLField(verbose_name='URL del video (YouTube)')),
                ('categoria', models.CharField(choices=[('psicologia', 'Psicología'), ('educacion', 'Educación'), ('tutorial', 'Tutorial'), ('motivacional', 'Motivacional'), ('capacitacion', 'Capacitación')], max_length=20, verbose_name='Categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('agregado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_agregados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
