# Generated by Django 4.2.11 on 2026-05-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0014_alter_consejoproceso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='videos/covers/', verbose_name='Imagen de portada'),
        ),
    ]
