# Generated by Django 6.0.3 on 2026-06-05 05:51

import matriculas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0015_video_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=matriculas.models.archivo_libro_storage, upload_to='libros/', verbose_name='Archivo PDF'),
        ),
    ]
